/* Generated by vite-plugin-env-parser */

declare module 'vite-env' {
  readonly const VITE_PORT: number
  readonly const VITE_YOUR_NAME: string
  readonly const VITE_YOUR_AGE: number
  const VITE_IS_IKUN: boolean
  const VITE_KUN_JOBS: string
  const APP_YOUR_NAME: string
  const APP_YOUR_AGE: string
  const APP_IS_IKUN: string
}
