/* Generated by vite-plugin-env-parser */

declare module "vite-env" {
  readonly const VITE_PORT: number
  readonly const VITE_YOUR_NAME: string
  readonly const VITE_YOUR_AGE: number
  readonly const VITE_IS_IKUN: boolean
  readonly const VITE_KUN_JOBS: string
  readonly const APP_YOUR_NAME: string
  readonly const APP_YOUR_AGE: string
  readonly const APP_IS_IKUN: string
  readonly const APP_KUN_JOBS: string[]
}
