import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { DTS, ViteEnv, ParsedValue } from './types'

export function generateDTS(dts: DTS, root = process.cwd(), env: ViteEnv = {}) {
  if (!dts) return
  dts = dts === true ? 'src/env.d.ts' : dts
  const path = resolve(root, dts as string)
  const doWriteFileApi = writeFileSync
  doWriteFileApi(path, createDTSContent(env), 'utf-8')
}

export function createEnvCode(env: ViteEnv = {}) {
  let envCode = ''
  let exportKeys = ''
  for (const key in env) {
    exportKeys += `${key}, `
    const value = env[key]
    envCode += `
    export const ${key} = ${['string', 'object'].includes(typeof value) ? JSON.stringify(value) : value}`
  }
  return `${envCode}
  export default { ${exportKeys.slice(0, -2)} }`
}

function createDTSContent(env: ViteEnv = {}): string {
  // TODO: resolve content by injectAtEnd
  const getType = (v: ParsedValue | ParsedValue[]) => `${typeof (Array.isArray(v) ? v[0] : v)}${Array.isArray(v) ? '[]' : ''}`
  const envContent = Object.entries(env).reduce((cur, [key, value]) => `${cur}
  readonly const ${key}: ${getType(value)}`, '')
  return `/* Generated by vite-plugin-env-parser */

declare module "vite-env" {${envContent}
}
`
}
